import re

from flask import render_template, request, abort

from radio import app


@app.route('/', methods=('GET',))
def index():
    return render_template('index.html')


@app.route('/pay', methods=('GET', 'POST'))
def pay():
    if request.method == 'GET':
        app.logger.info('Someone at entering their information and paying.')
        return render_template('pay.html')
    else:
        # So, generally, for speed there is a client-side validation, but for
        # safety (i.e. people like David modifying the source code) we also
        # implement an identical server-side validation.  If server-side fails,
        # we return a 400 bad request.

        name = request.form['name'].strip()
        email = request.form['email'].strip()
        wechat = request.form['wechat'].strip()
        app.logger.info('Someone is here attempting to access the QR code.\n'
                        f'\tname: {name}, email: {email}, wechat: {wechat}')

        # Simple validation on if the email is of ykpaoschool.cn domain.
        ykps_email = re.fullmatch(r'[A-Za-z0-9\._-]+@(stu\.)?ykpaoschool\.cn',
                                  email)

        if not name or not ykps_email or not wechat:
            return abort(400)
        else:
            # TODO, at this point, there should be some unique random ID or
            # cookie assigned to the client, so that this QR code is not
            # otherwise accessible.  This might be some token generated by us
            # or WeChat?
            #
            # Store the to-be-processed ID to be corresponding to the name and
            # other info in some temporary buffer like a dict.
            return render_template('qr.html',
                                   name=name, email=email, wechat=wechat)


@app.route('/add', methods=('POST',))
def add():
    name = request.form['name']
    email = request.form['email']
    wechat = request.form['wechat']
    app.logger.info('Someone at the cell-editing page.\n'
                    f'\tname: {name}, email: {email}, wechat: {wechat}')
    return render_template('add.html',
                           name=name, email=email, wechat=wechat)
